name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your ideas help make Faith & Flourishing better for teens.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - CBT/Mental Health
        - Faith Integration
        - User Interface
        - User Experience
        - Admin/Management
        - Authentication/Security
        - Performance
        - Accessibility
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Critical - Blocks usage
        - High - Significantly improves experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Primary Audience
      description: Who would benefit most from this feature?
      options:
        - Teens (Primary Users)
        - Parents/Guardians
        - Counselors/Therapists
        - Faith Leaders
        - Administrators
        - Everyone
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, sketches, or examples from other apps
      placeholder: Drag and drop images here or paste links

  - type: textarea
    id: research
    attributes:
      label: Supporting Research/Evidence
      description: For CBT/mental health features, any supporting research or evidence-based rationale?
      placeholder: Studies show that...

  - type: textarea
    id: theological
    attributes:
      label: Theological Considerations
      description: For faith-based features, any relevant scripture, Church teaching, or theological considerations?
      placeholder: Based on Catholic teaching...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any other details...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help with this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
          required: false
        - label: I can help with content/research
          required: false
        - label: I can help with design/mockups
          required: false
        - label: I can help test this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues and discussions to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with the mission of Faith & Flourishing
          required: true
        - label: This feature would benefit the teen users
          required: true

